config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  # resources :tweets, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
  resources :tweets do
    resources :comments, only: %i[new create]
    resources :likes, only: %i[create destroy]
  end
  resources :users, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true
  validates :user, presence: true
  validates :tweet, presence: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :likes_count

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true
  validates :user, presence: true
  validate :image_presence

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  private

  def image_presence
    errors.add(:image) unless image.attached?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  validates :name, presence: true, length: { maximum: 10 }, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(tweet_id: params[:tweet_id], user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    like.destroy
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :move_to_index, except: %i[index show]
  before_action :set_tweet, only: %i[show edit]

  def index
    @q = Tweet.ransack(params[:q])
    @tweets = @q.result(distinct: true).order('created_at DESC').page(params[:page]).per(6)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to root_path
  end

  def edit; end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
      redirect_to root_path, notice: '投稿を更新しました。'
    else
      redirect_to root_path, notice: '更新に失敗しました。'
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
      redirect_to root_path, notice: '削除に成功しました。'
    else
      redirect_to root_path, notice: '削除に失敗しました。'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.order('created_at DESC').page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(6).order('created_at DESC')
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NpbBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">プロ野球掲示板</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if user_signed_in? %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/tweets/new">投稿する <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/users">ユーザー一覧 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>さん
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/<%= current_user.id %>">マイページ</a>
                <a class="dropdown-item" href="#">プロフィール</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/users/sign_in">ログイン <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/users/sign_up">新規登録 <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        <% end %>
        </div>
      </nav>

      <%= yield %>

      <footer class="py-4 bg-dark text-light">
        <div class="container text-center">
          <p>©️プロ野球掲示板</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless tweet.like_user(current_user.id).blank? %>
    <%= link_to tweet_like_path(tweet_id: tweet.id, id: tweet.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="fas fa-heart">いいね</i>
        <span class="text-secondary">
          <%= tweet.likes_count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to tweet_likes_path(tweet.id), method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="far fa-heart">いいね</i>
        <span class="text-secondary">
          <%= tweet.likes_count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if tweet.likes_count.to_i > 0 %>
    <div class="vertical_like">
      <i class="fas fa-heart">いいね</i>
      <span class="text-secondary">
        <%= tweet.likes_count %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      <i class="far fa-heart">いいね</i>
      <span class="text-secondary">
        <%= tweet.likes_count %>
      </span>
    </div >
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'likes/like', locals: { tweet: @tweet }) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'likes/like', locals: { tweet: @tweet }) %>");

app/views/tweets/_form.html.erb
<div class="border w-75 p-3 mx-auto">
  <%= form_with model: tweet, local: true do |f| %>
    <div class="form-group">
      <%= f.label :タイトル %>
      <%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力", id: "title" %>
    </div>
    <div class="form-group">
      <%= f.label :画像を選択 %>
      <%= f.file_field :image, class: "form-control-file", id: "image" %>
    </div>
    <div class="form-group">
      <%= f.label :テキスト %>
      <%= f.text_area :text, class: "form-control", rows: 8, id: "text" %>
    </div>
    <%= f.submit "投稿する", class: "w-100 btn btn-primary d-block mx-auto" %>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="article-all"><p>投稿一覧</p></div>
<div class="card-columns">
  <% tweets.each do |tweet| %>
    <div class="card mt-3" >
      <%= link_to image_tag(tweet.image, class: "card-img-top", alt: "ツイートの画像"), tweet_path(tweet) %>
      <div class="card-body p-3">
        <h5 class="card-title mb-0"><%=tweet.title %></h5>
      </div>
      <div class="card-body p-3">
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get, class: "card-link" %>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete, class: "card-link" %>
        <% end %>
        <div id="likes_buttons_<%= tweet.id %>", class="float-right">
          <%= render partial: 'likes/like', locals: { tweet: tweet } %>
        </div>
      </div>  
    </div>
  <% end %>
</div>
</div>
<div class="mx-auto mt-3">
  <%= paginate(@tweets) %>
</div>

app/views/tweets/edit.html.erb
<!-- メイン -->
<main>
  <!-- お問合せフォーム -->
  <div class="py-3">
    <div class="container">
      <h1 class="mb-3 text-center">投稿編集</h1>
      <!-- フォーム -->
      <%= render partial: "form", locals: { tweet: @tweet } %>
      <!-- /フォーム -->
    </div>
  </div>
  <!-- / お問合せフォーム -->
</main>
<!-- /メイン -->

app/views/tweets/index.html.erb
<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <h1 class="npb-blog-title text-white p-3 badge badge-primary">プロ野球掲示板</h1>
    <p class="lead">好きなプロ野球の話題について語り会おう！！</p>
    <%= search_form_for @q, class: "form-inline my-2 my-lg-0 d-block mx-auto" do |f| %>
      <%= f.search_field :title_cont, class: "form-control mr-sm-2", placeholder: "検索する" %>
      <%= f.submit "検索", class: "btn btn-success my-2 my-sm-0" %>
    <% end %>
  </div>
</div>
<div class="container">
  <%= render partial: "tweet", locals: { tweets: @tweets } %>
</div>

app/views/tweets/new.html.erb
<!-- メイン -->
<main>
  <!-- お問合せフォーム -->
  <div class="py-3">
    <div class="container">
      <h1 class="mb-3 text-center">新規投稿</h1>
      <!-- フォーム -->
      <%= render partial: "form", locals: { tweet: @tweet } %>
      <!-- /フォーム -->
    </div>
  </div>
  <!-- / お問合せフォーム -->
</main>
<!-- /メイン -->

app/views/tweets/show.html.erb
<div class="container">
  <h1 class="mb-3 text-center mt-3">投稿詳細</h1>
  <div class="container">
  <div class="card mb-3 w-75 h-75 mx-auto mt-3 pt-3">
  <%= image_tag(@tweet.image, class: "card-img-top w-50 h-50 mx-auto", alt: "ツイートの画像") %>
  <div class="card-body">
    <h5 class="card-title font-weight-bold">タイトル：<%= @tweet.title %></h5>
    <p class="card-text">本文：<%= @tweet.text %></p>
    <%# <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> %>
  </div>
  </div>
  </div>
  <div class="container w-75 h-75 border p-3 mb-3">
  <% if current_user %>
    <%= form_with model: [@tweet, @comment], local: true do |f| %>
      <div class="form-group">
        <%= f.text_area :text, class: "form-control", rows: 3, placeholder: 'コメントを入力してください' %>
        <%= f.submit "送信する", class: "btn btn-primary my-2 d-block mx-auto w-50" %>
      </div>
    <% end %>
  <% end %>
  <div class="comments">
    <h4 class="text-center">＜コメント一覧＞</h4>
    <% if @comments %>
      <ul class="list-group">
        <% @comments.each do |comment| %>
          <li class="list-group-item">
            <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">  
  <div class="article-all py-3"><p>ユーザー一覧</p></div>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-md-6 offset-md-4 mx-auto">
        <div class="media bg-light shadow d-flex align-items-center">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "user-img rounded-circle", alt: "ユーザーの写真"  %>
          <% else %>
            <%= image_tag "https://www.loginradius.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png", class: "user-img rounded-circle", alt: "ユーザーの写真" %>
          <% end %>
          <div class="col">
            <p><%= link_to user.name, user_path(user) %>さん</p>
          </div>
          <div class="float-right">
            <% unless current_user == user %>
              
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
  <div class="mx-auto mt-3">
    <%= paginate(@users) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <% if @user.avatar.attached? %>
    <div class="user_image"><%= image_tag @user.avatar, class: "rounded-circle", id: "circle" %></div>
  <% else %>
    <div class="user_image"><%= image_tag "https://www.loginradius.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png", class: "rounded-circle", id: "circle" %></div>
  <% end %>
  <h1><span class="badge badge-primary"><%= @user.name %>さんのマイページ</span></h1>
</div>
<div class="container">
  <%= render partial: "tweets/tweet", locals: { tweets: @tweets } %>
</div>